- block:
  - name: Install python3
    yum:
      name: "{{python_version_meta.RedHat[python_version]}}"
      update_cache: yes

  - name: Install python3-devel
    yum: 
      name: python3-devel
  when: ansible_distribution != 'Amazon'

- block:
  - name: Install python3
    shell: |
      sudo amazon-linux-extras install python{{ python_version }}
      sudo rm -rf /usr/bin/python
      sudo rm -rf /usr/bin/python3
      sudo ln -s /usr/bin/python3.8 /usr/bin/python
      sudo ln -s /usr/bin/python3.8 /usr/bin/python3
      sudo rm -rf /usr/bin/pip3
      sudo ln -s /usr/bin/pip3.8 /usr/bin/pip
      sudo ln -s /usr/bin/pip3.8 /usr/bin/pip3
      sudo yum remove python3.7 -y
      sudo yum install python3-devel -y
  when: ansible_distribution == 'Amazon'

- block:
## pip needs to install Python-devel to install uwsgi
  - name: Install rh-python38-python-devel
    yum:
      name: "rh-python38-python-devel"

  - name: Create link for python3
    file:
      src: '{{item.src}}'
      dest: '{{item.dest}}'
      state: link
      force: yes
    with_items:
      - {src: '/opt/rh/{{python_version_meta.RedHat[python_version]}}/root/bin/python{{python_version}}',dest: '/usr/bin/python{{python_version}}'}  
      - {src: '/opt/rh/{{python_version_meta.RedHat[python_version]}}/root/bin/pip-3.8',dest: /usr/bin/pip3} 

  - name: copy python_scl.sh
    template:
      src: python_scl.sh
      dest: /etc/profile.d

  - name: Enable python3
    shell: source /etc/profile.d/python_scl.sh
    args:
      executable: /bin/bash
  when: python_version == "3.8" and ansible_distribution != 'Amazon'
  
  

  

